### ISSUE TITLE
Flipped flip cards considered as having color indicators

### ISSUE THREAD

**Issue by fenhl** [taw/magic-search-engine#108]
In #5, a non-issue was reported stating that the mana cost on flipped flip cards, such as [Autumn-Tail, Kitsune Sage](https://mtg.wtf/card/chk/28b), should be removed. I say non-issue because both halves of a flip card have the same mana cost, as was pointed out in #5's discussion. This appears to have been changed at some point after the report of #5, so that Autumn-Tail now shows no mana cost, and instead shows the text “(Color indicator: Autumn-Tail, Kitsune Sage is white)” and also appears in the [`in:W`](https://mtg.wtf/card?q=in%3AW) query. This is incorrect, as Autumn-Tail does not have a color indicator; it doesn't need one because its mana cost already makes it white.

**Comment by taw** [comment]
So success criteria:

- [x] flip cards should have no mana cost in title line, as that'd match what's on the card, and it was seriously confusing
- [ ] color should be somehow indicated in text part of the display, without adding mana cost to title line
- [ ] it shouldn't match `in:` or say "color indicator"
- [ ] decklist entries for them should look reasonable. [I don't think they do now](https://mtg.wtf/deck/c18/natures-vengeance) - "Budoka Gardener // Dokai, Weaver of Life {1}{G}/" in style of split cards is a bit eh. [It looks reasonable on split cards](https://mtg.wtf/deck/cmd/mirror-mastery).
- [ ] technically they have mana cost in game when flipped, I'm not really convinced that they should match `mana:` queries, or that they shouldn't
- [x] they should match `cmc:` query 
- [x] they should match all `c:`/`ci:` queries

So should it just say "(Dokai, Weaver of Life is green)" instead of "(Color indicator: Dokai, Weaver of Life is green)" ? Using some kind of `invisible_color_indicator` flag?

Alternatively it could have mana cost, just some kind of `hide_mana_cost` flag for flipped cards.

**Comment by fenhl** [comment]
Maybe instead of the color indicator line, it could say something like “(Dokai, Weaver of Life is green since it inherits the mana cost of {1}{G} from Budoka Gardener.)”

**Comment by fenhl** [comment]
I do think that it should match `mana={1}{G}`. Using a `hide_mana_cost` flag that moves the mana cost from the name line to the auto-generated reminder text could meet this requirement.

**Comment by taw** [comment]
It's using `hide_mana_cost` flag. I'm not really into reminder text I wrote for flipped cards. All queries should match game rules now.

**Comment by taw** [comment]
Wait, did we fix this one?

**Comment by fenhl** [comment]
Yes.

**Comment by taw** [comment]
All right, closing. It's been a while since I did a proper cleanup of old issues here.
