### ISSUE TITLE
Color Indicator

### ISSUE THREAD

**Issue by FM-96** [taw/magic-search-engine#13]
I think it would be great to have a mention of when a card has a color indicator.

As it is, there is absolutely no indication that [Pact of Negation](https://mtg.wtf/card/fut/42) isn't colorless, for example.

**Comment by taw** [comment]
Great point.

**Comment by taw** [comment]
I added them, but there's still an issue of what would be good formatting to cover all cases like:

* [devoid](http://mtg.wtf/card/bfz/128)
* [pacts/cards with no mana cost](http://mtg.wtf/card/fut/42)
* [DFCs](http://mtg.wtf/card/isd/181b)
* [Ghostfire](http://mtg.wtf/card/fut/115)
* [Transguild Courier](http://mtg.wtf/card/di/168)

That's because devoid and Ghostfire have it in rules text, DFCs and cards with no mana costs have it as indicator, and Transguild Courier got Oracle text which is basically unprintable.

**Comment by fenhl** [comment]
It's important to note that cards with devoid and Ghostfire *don't* have a color indicator, which might be relevant in corner cases.

**Comment by taw** [comment]
Yeah, mtgjson for some reason doesn't store color indicator, just card colors, and I can check them against mana colors to see if they mismatch.

Right now I just print "color indicator" for all mismatching cases.

It seemed like Wizards switched from rules text to color indicator, then changed their mind with devoid, so it's a mess.

**Comment by FM-96** [comment]
I don't think it's a mess. Color indicators are just for colors. Making cards *colorless* is done via rules text.

That is, in my opinion, how you should implement it too. Cards like Crumble to Dust and Ghostfire now have duplicate information in your app. (Devoid and your color indicator and straight up "~ is colorless" and your color indicator, respectively.)

By the way, I just want to say that I think it's awesome that you've responded to this so fast.
👍

**Comment by taw** [comment]
Yeah, they removed all text from it, but there's no card with "all colors" color indicator, so their Oracle printing is just weird.

**Comment by FM-96** [comment]
Well, I mean... there is one: Transguild Courier.

If they ever were to reprint it, it would have a WUBRG color indicator on it. The fact that no card has ever actually been *printed* with one doesn't mean it doesn't exist.

"~ is all colors" is just as outdated as "Summon Legend" now.

**Comment by taw** [comment]
OK, I made colorless cards not have color indicators, everything else does them like before.
