### ISSUE TITLE
Exact search doesn't find "Ach! Hans, Run!"

### ISSUE THREAD

**Issue by pdgwien** [taw/magic-search-engine#14]
When trying to search for "Ach! Hans, Run!" (http://mtg.wtf/card/uh/116) in exact mode (!"Ach! Hans, Run!"), the card is not found.

**Comment by taw** [comment]
I'm not even surprised by this one, but yeah, I'll get it fixed.

**Comment by taw** [comment]
Three uncards were broken:

* ["Ach! Hans, Run!"](http://mtg.wtf/card?q=!%22Ach!+Hans%2C+Run!%22)
* [Look at Me, I'm R&D](http://mtg.wtf/card?q=%21Look+at+Me%2C+I%27m+R%26D)
* [R&D's Secret Lair](http://mtg.wtf/card?q=%21R%26D%27s%20Secret%20Lair)

But now I see that R&D cards don't work for regular search. The reason is simple - `&` is one of split card separators (even if `//` is more common), so it's looking for split cards.

It will need some special case for it too.

**Comment by taw** [comment]
And it all works now.
