### ISSUE TITLE
Searching by foreign name matches whole words

### ISSUE THREAD

**Issue by KRE02** [taw/magic-search-engine#142]
When searching for cards by their foreign language name, the search matches whole words.
For example, searching for "The Magic Mirror" by its german Name "Der Zauberspiegel" with query expression: `de:Zaubers` does not find anything. Searching for `de:Zauberspiegel` does find the card. Searching without specifying the language (english) with query `magic mirr` finds the card.
As a “workaround”, searching via regex works: `de:/Der Zaubers.*/` 

Expected behaviour:
When searching cards by their foreign name, do not match full words only.

**Comment by taw** [comment]
Looks like I specifically made this change for all languages except Asian languages back in 2018. Git comment for that change says something about `foreign:"word"` getting far too many false matches, but I don't really remember the specifics.

I guess German should also be added to the list, since it doesn't have many word separators.

For a really simple workaround, I think `de:/Zaubers/` already does exactly what you want `de:"Zaubers"` to do, but I'll make this the default for German.

**Comment by taw** [comment]
`de:"..."` query changed to be like Asian languages.

`foreign:"..."` still has old logic.
