### ISSUE TITLE
Filtering out "non-maindeckable" cards

### ISSUE THREAD

**Issue by glaebhoerl** [taw/magic-search-engine#217]
If I search for things using e.g. `f:pauper`, Stickers and Attractions are included. (Meanwhile Dungeons are not. I guess the logic behind this might be that Dungeons don't go into *any* deck, while the others can be part of your "attractions deck" and so on?)

In any case, I don't want to see any of them. Is there an easier way to filter them out than `-t:stickers -t:attraction`? Bonus points if it can also cover `-is:draft`, which I also basically never want to see. :)

**Comment by taw** [comment]
So to check legality situation:

I thought Dungeons are tokens not cards, and tokens don't have legality, [but rules actually define them as cards](https://mtg.wtf/help/rules#section-309-1). In any case, they are not part of deck construction.

Attractions are part of deck construction, have well defined legality, with 22/50 being legal in eternal formats, so that's a meaningful thing to include.

Stickers are part of deck construction, and are all currently legal in eternal format.

I see what you mean, but I'm not sure what would be a good query for it.

**Comment by glaebhoerl** [comment]
Brainstorming:

As a narrow solution to the "but is it part of *main deck* deck construction" question, an `is:maindeck` predicate seems like the easy answer. In a tournament-constructed context it'd filter out stickers and attractions; in a more general context maybe also Vanguard or Contraptions, and I'm not sure what else is out there (planes?). It's only mildly shorter than `-t:stickers -t:attraction` but at least it has a principled definition and might well expand to include more things in the future.

As a broader net (covering "I basically never want to see X" for any particular X, and beyond), are you averse to having a "default query" text field on the Settings page, the contents of which would get pre-loaded into the search field on the main page? (So that you can still edit/delete it.)

**Comment by taw** [comment]
I have "extra" flag that's calculated as (layout:vanguard or layout:planar or layout:scheme or t:conspiracy) which is used for skipping format legality checks and not really otherwise exposed. But that's not the same, as Stickers and some Attractions are Vintage-legal.

We could probably do `is:maindeck` if we can make a definite list. Would this be the whole list:

* t:plane
* t:phenomenon
* t:vanguard
* t:scheme
* t:conspiracy
* t:stickers
* t:attraction

Then again, they can't go into sideboard either, so I'm not sure this is a good name.

**Comment by glaebhoerl** [comment]
t:contraption and it would seem t:hero as well (found by subtracting known types to see what was left, so if any are still missing they would be subtypes of the normal card types).
https://mtg.fandom.com/wiki/Contraption https://mtg.fandom.com/wiki/Hero_(card_type)

Unfortunate that `t=dungeon` isn't perfect either because one has Undercity also in its subtype. `t:hero` has a similar situation with a false positive and subtypes :shrug:

**Comment by taw** [comment]
Right, let's get it done.

[Is this the correct query](https://mtg.wtf/card?q=-%28t%3Aplane+or+t%3Aphenomenon+or+t%3Avanguard+or+t%3Ascheme+or+t%3Aconspiracy+or+t%3Astickers+or+t%3Aattraction%29+-%28t%3Ahero+-t%3Acreature%29+-%28t%3Adungeon+-t%3Aplaneswalker%29+t%3Adungeon), or is there some card that it gets wrong?

**Comment by axxroytovu** [comment]
You missed contraptions

Is there any benefit to separating these into `deck:maindeck`? Then we could add other `deck:` types, including `planechase`, `heros_path`, `attraction`, `sticker`, `contraption`, `learn`, `archenemy`, etc.?

**Comment by taw** [comment]
We'd need to pick a different keyword, and wouldn't most of them already have very simple queries?

I should probably add alias for w:herospath, as that's simple but not obvious.

**Comment by glaebhoerl** [comment]
> Is this the correct query

Looks good to me.

**Comment by taw** [comment]
[For added fun there's one non-Hero card with watermark herospath, at least according to mtgjson data](https://mtg.wtf/card/pjou/162/Hall-of-Triumph).

**Comment by taw** [comment]
I added two queries and their negations (is:dungeon was already working):

* [https://mtg.wtf/card?q=is%3Adungeon](is:dungeon)
* [https://mtg.wtf/card?q=is%3Ahero](is:hero)
* [https://mtg.wtf/card?q=not%3Amaindeck](not:maindeck)

Can you verify that everything is exactly right?

**Comment by glaebhoerl** [comment]
Thanks :)

I'm not any kind of authority on the subject but they do seem to match what's been discussed above as far as I can tell.

**Comment by taw** [comment]
OK, closing the ticket. Feel free to reopen if you find something wrong with the query.

**Comment by taw** [comment]
[This is somewhat relevant, we now have decklimit= queries](https://github.com/taw/magic-search-engine/issues/254).

I think "non-maindeckable" cards maybe should have decklimit=0.
