### ISSUE TITLE
Direct card lookup is broken

### ISSUE THREAD

**Issue by fenhl** [taw/magic-search-engine#31]
Looking up a card directly by name (`!Card Name`) produces an error message. [Example](https://mtg.wtf/card?q=%21Dryad+Arbor)

> We're sorry, but something went wrong.
>
> If you are the application owner check the logs for more information.

**Comment by silasary** [comment]
Linked example works for me

**Comment by taw** [comment]
Fixed now.

The protocol for passing metadata between frontend and backend was not properly tested because it used to be trivial, and the metadata is mostly not very significant (and generally empty).

Adding parser warnings made `!`-queries and other queries mismatch in how they pass warnings to the frontend, and apparently there wasn't a single `!`-query test that hit frontent as well.

This whole file https://github.com/taw/magic-search-engine/blob/master/frontend/app/controllers/card_controller.rb is messy and duplicates functionality with `CLIFrontend`.

For extra bonus `FIXME` tag predicting something like that will happen, 14 lines above crash line.
