### ISSUE TITLE
Basic land watermarks missing

### ISSUE THREAD

**Issue by fenhl** [taw/magic-search-engine#44]
The big mana symbol watermarks on basic lands are not showing up. [This seems to be deliberate.](https://github.com/taw/magic-search-engine/commit/9b18628f2ee91e2ddc3ff7df4044e26e6f61eed9#diff-44392392ca7d32d0aa276eac0fa5e7a8R292) Why?

**Comment by taw** [comment]
How are these symbols watermarks? They don't seem like the same thing.

**Comment by fenhl** [comment]
Well, they're big logos in the text box which aren't part of the rules text. If they're not officially watermarks (and I haven't found anything official suggesting that they are or aren't), they're at least pretty close, so it makes sense to incorporate them into the `w:` feature.

**Comment by taw** [comment]
Gatherer doesn't list them as watermarks and it lists all watermarks, so officially they aren't. ([example](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=366291),
[example](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=426960))

I've never heard anyone refer to those basic land symbols as watermark ([example](https://mtg.gamepedia.com/Watermark)) before recent mtgjson change.

**Comment by taw** [comment]
That symbol is basically a weirdly formatted reminder text, and it only goes on basic lands.

**Comment by silasary** [comment]
They've been called "Watermarks" in Magic Set Editor (a custom card creator) for over a decade.

But I think that's for technical reasons, and I've never seen it spread outside of that.

**Comment by silasary** [comment]
Note that gatherer has the `Printed Text` on Plains as "W".  Which backs up the fact that it's just an oversized text element, and not a watermark.

**Comment by taw** [comment]
Yeah, it's treating this printed oversized "{W}" as reminder text, so ignoring it like all other reminder text.

I'm not sure they have much value in this search, it's literally just basic lands and nothing else.

That reminds me, I never added card text search (`ct:` on MCI), probably due to index size to usefulness ratio. Would anybody actually use it?

**Comment by silasary** [comment]
It's fun to find archaic wording.  I once used it to build a commander deck built entirely with cards that would make a modern player confused/laugh.

But no, it's probably not that valuable.

**Comment by taw** [comment]
I think we can close this one.

As somewhat related bit, I added reminder text like `({T}: Add {W} to your mana pool.)` or `
({T}: Add {U} or {R} to your mana pool.)` on cards with basic land types as exception to the usual "no reminder text" policy. The text box looked weird otherwise.

It's still not treated as searchable Oracle text, as technically reminder text does nothing.

**Comment by silasary** [comment]
This reminder text exists on some dual lands already (see [Shocklands](http://mtg.wtf/card?q=is%3Ashockland)).  

I'm happy with inserting it consistently on all cards with basic land types.

**Comment by taw** [comment]
Yeah, I added it there to shocklands etc. a few days ago as part of this change.

**Comment by silasary** [comment]
No, I'm talking about it being literally printed on the physical cards :)
