### ISSUE TITLE
Lands have incorrect images

### ISSUE THREAD

**Issue by fenhl** [taw/magic-search-engine#49]
For example, [_Amonkhet_ Plains 257](https://mtg.wtf/card/akh/257) has the image for Plains 250.

**Comment by taw** [comment]
Yeah, there's no consistent way to match hq scans with multiple printings within same set. Like what their `plains1` matches to is anyone's guess. I'm surprised this problem doesn't happen more often.

So I now added one. [New view looks like this](http://mtg.wtf/set/akh/verify_scans) - URL is generated by simply appending `/verify_scans` to [anything from set list](http://mtg.wtf/set).

Columns are: HQ scan, LQ scan (Gatherer), relevant information to validate.

Maybe I could also limit this to just cards with multiple copies per set, but I've had a couple of mtgjson bugs that resulted in totally mangled data before. 

It shouldn't be too much work for me to go a quick visual scan of this every time set gets new hq scans, but going back to validate everything... Reported mismatches definitely welcome.

**Comment by taw** [comment]
OK, so I checked all duplicates.

Here are all sets that need fixing. Usually basic lands for newer sets, and alt art for older sets:

- [x] Amonkhet
- [ ] Planechase Anthology
- [ ] Commander 2016
- [ ] Duel Decks: Nissa vs. Ob Nixilis
- [ ] Conspiracy: Take the Crown (special foil Kaya)
- [ ] Zendikar
- [ ] Lorwyn
- [ ] Planeshift (★ cards)
- [ ] Super Series (not on Gatherer at all, but collector numbers look all messed up)
- [ ] Battle Royale Box Set
- [ ] Starter 1999
- [ ] Anthologies
- [ ] Portal Second Age
- [ ] Portal (it seems broken on both, between remainder-text and no-reminder-text versions)
- [ ] Vanguard
- [ ] Fifth Edition
- [ ] Mirage
- [ ] Alliances
- [ ] Chronicles
- [ ] Ice Age
- [ ] Fourth Edition
- [ ] Media Inserts
- [ ] Fallen Empires
- [ ] Antiquities
- [ ] Unlimited Edition


And here are sets that mismatch because they're broken on Gatherer:

- [x] Beatdown Box Set (this is reverse case, as hq pics are correct, but Gatherer pics of Swamp are all same)
- [x] Classic Sixth Edition (hq pics correct, Gatherer pics all same)
- [x] Tempest (all are by same artist and no on-card numbers, so anybody's guess which one is meant to be witch, Gatherer pics all same)
- [x] Homelands

And there's also:

- [ ] Arabian Nights (it lists alt art but neither hq scans nor gatherer have them)

**Comment by taw** [comment]
Everything done except for https://github.com/taw/magic-search-engine/issues/50 which is data source problem.

Browser cache will probably still show bad pics unless disabled.
