### ISSUE TITLE
Time: operator should maybe reflect errata.

### ISSUE THREAD

**Issue by silasary** [taw/magic-search-engine#51]
Firstly, feel free to WONTFIX this.  This is a ridiculous request.

Many cards have received functional errata over the years. While some a simple things, others are very much not.

What I'm asking is for [Burning of Xinye time:2007](http://mtg.wtf/card?q=Burning+of+Xinye+time%3A2007) to return the oracle text `Each player sacrifices four lands. Burning of Xinye deals 4 damage to each creature.` (ie, the oracle text it had between the *[Morningtide](https://yawgatog.com/resources/oracle-changes/lrw-mor/?id=4#s0)* and *[Masters Edition III](https://yawgatog.com/resources/oracle-changes/m10-hop/?one=Dburning-of-xinye)* erratas)

**Comment by fenhl** [comment]
Where would we even get this data?

**Comment by silasary** [comment]
[Yawgatog](https://yawgatog.com/resources/oracle-changes/) has a comprehensive list of every change post-Ravnica.  (Albeit not in a machine readable format)

**Comment by taw** [comment]
Well, first someone would need to create a data source, so that's more mtgjson request, or creating some fork of that.

If someone feels like Magic historian, this information could sort of be gathered from:

* We have original printing text (which we don't currently index, but it's there)
* One could use mtgjson's git history to get (relatively recent) old Oracle wordings - there's a lot of cleanup necessary here, but it's mostly machine readable
* There's update bulletins, that Yawgatog site you just linked, and maybe even web.archive.org to get more data
* If I understand correctly, in the olden days the only way cards would update was with new releases, so comparing original wording between printings could reconstruct early days' changes.

So I guess if someone really felt like putting the effort, they could create data source.

I'm definitely not volunteering, getting historical banlist changes was already too much work (related: https://github.com/taw/magic-search-engine/issues/52 ) for feature that sees fairly limited use.

If mtgjson ever decides to include that history, it would be relatively straightforward to search that (except for awkward index size issues).

**Comment by fenhl** [comment]
This seems like another potential use-case for a manually maintained extension to MTG JSON, as [previously discussed](https://github.com/mtgjson/mtgjson/issues/287#issuecomment-323070767).

**Comment by taw** [comment]
It's much bigger project than just adding a bunch of IDs.

Indexer can easily be adapted to add non-mtgjson data sources if there's ever good need for that.

**Comment by taw** [comment]
Closing this as not really possible until someone makes a machine readable version of Oracle history.
