### ISSUE TITLE
Search by name, part 2

### ISSUE THREAD

**Issue by fenhl** [taw/magic-search-engine#66]
As a follow-up to #24, I have some additional feature requests:

* You can use `n:regex` and `name=text`, but none of the following:
    * `name:regex`
    * `n:text`
    * `name:text`
    * `n=text`
* It would be useful to have some sort of syntax that will search for a card name in all languages, for example if you have a card but don't know the language.

**Comment by taw** [comment]
These are just coincidentally similar, `name=` works because it's mainly there for `name>` and such, but it's easy to add missing versions.

I wanted to do `*:gideon` style of search for very long time, but there are some special cases there. Like [`*:"green haste elemental"`](http://mtg.wtf/card?q=c%3Ag+o%3Ahaste+t%3Aelemental). I even thought about making it default (instead of `name:`), but first it needs to exist.

**Comment by taw** [comment]
The aliases are deployed now. The bigger question of `*:` matcher will probably have to wait.

**Comment by taw** [comment]
Closing because of https://github.com/taw/magic-search-engine/issues/72
