### ISSUE TITLE
Random card button 

### ISSUE THREAD

**Issue by fenhl** [taw/magic-search-engine#70]
A button to get a random card from a query, as discussed in https://github.com/taw/magic-search-engine/pull/22#issuecomment-280884887, has been requested again by people who want to play Momir Basic using my fork. The differences to the already implemented `sort:rand` would be that the result would be different each time and that repeated use could produce duplicate results.

**Comment by taw** [comment]
sort:rand feels a bit silly in not actually being random, but this way pagination works.
I think the only way to make it work is by making frontend aware of it, so pagination gets some random seed, then sort:rand can be actually random.

**Comment by taw** [comment]
That's fixed now. New behaviour is that `sort:rand` is actually random.

For any query including `sort:rand`, pagination links now include random seed arguments, so paginating  random query works perfectly fine, but if you press search again you get completely different results.

It's still not 100% right for Momir Basic, as cards with more printings are more likely to show up. I guess `sort:rand not:reprint` would be more accurate, but there could be some minor intricacies of `not:reprint` logic (like prerelease promos and otherwise cards with same date).
