### ISSUE TITLE
Printed in language

### ISSUE THREAD

**Issue by fenhl** [taw/magic-search-engine#74]
A filter for cards that have been printed in a specific language would be useful, such as `de:*`.

**Comment by taw** [comment]
This sounds like a wonderful idea. There are some problems with it.

We don't actually record foreign printings in database, just foreign names, without any record where it's coming from.

That's mainly because it's very common for the same card to be printed under multiple different names in same language. [Here's example](http://mtg.wtf/card/m12/220/Thran-Golem).

It was "Golem dos Thran" and "Golem Thran" in its various Portuguese printings.
Also "Голем Трана" and "Транский Голем" in its various Russian printings.

It's also the problem the other way around, multiple different cards can have same foreign name, for example Italian ["Eliminare"](http://mtg.wtf/card?q=it%3AEliminare) was both "Cancel" and "Wipe Away".

And so to normalize that away a bit, we just dump them at card level. So `e:al jp:*` will return every printing of a card from alpha which had Japanese printing sometime later.

Another issue is that [French names of Unhinged cards](http://mtg.wtf/card?q=st%3Aun+fr%3A*) are official, even though they were never actually printed.

With these caveats, it's now deployed.

There's other stuff that needs to be done about foreign name search:

* add regexp search
* default to full word match so `foreign:red` doesn't match half the cards (and therefore so `all:red` doesn't match something just because it's `it:"Predatore Eteride"`
* and maybe we could actually record which printing was in which languages.

**Comment by taw** [comment]
Foreign language regexp search now also added so [`de:/\w{20,}/`](http://mtg.wtf/card?q=de%3A%2F%5Cw%7B20%2C%7D%2F+view%3Afull) does what you can guess it would.
