### ISSUE TITLE
is:primary for split cards

### ISSUE THREAD

**Issue by fenhl** [taw/magic-search-engine#76]
I need a way to filter out the right half of each split card. I tried `is:primary` but that doesn't seem to work.

**Comment by taw** [comment]
Well, both of them are on the front side, so both of them count as `is:primary`.

I could think of no way to query this, so I added `number:123` and `number:/regexp/` operators.

`is:split number:/a/` happens to get left sides of spit cards, but that's sort of because the indexer forces unique numbers, and adds `a`, `b` for such cards, and I think it generally does `a` for left.

An obvious followup would be `number>100`. It's a bit nontrivial as order is `10, 10a, 10b, 11, 11a, 11b, ..., 100, 100a, 100b, ...`

**Comment by taw** [comment]
Added `number>` etc. too

**Comment by fenhl** [comment]
That works.
