### ISSUE TITLE
Monkey Cage has outdated Oracle text

### ISSUE THREAD

**Issue by fenhl** [taw/magic-search-engine#8]
Compare https://mtg.wtf/card/mm/307 and http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=19878.

**Comment by taw** [comment]
This kind of updates were usually dealt with by mtgjson, and mtg.wtf didn't do any gatherer updates, but it's recently been a mess (more or less since getting new maintainers).

This is currently blocking mtgjson update: https://github.com/mtgjson/mtgjson/issues/240 ( also with other projects relying on mtgjson like https://github.com/Cockatrice/Cockatrice/issues/2207 ).

I'd rather not fork mtgjson, but I might have to if they don't get their act together :-/

**Comment by fenhl** [comment]
The mtgjson team is focusing on the release of version 4, and is unlikely to fix this in v3 anymore.

**Comment by taw** [comment]
I'd say slightly outdated Oracle text is something I'm willing to live with for a while.

In longer term, we have a few choices:

* mtgjson gets better on its own (hopefully)
* we use faulty mtgjson, but maintain a bunch of validations and fixes in the indexer (that's where it's currently going)
* we fork mtgjson and fix it there - but that's a fairly dreadful codebase, so I'd rather not
* we get data directly from Gatherer (and supplement it with other sources) - it's not quite as straightforward as Gatherer data also has a lot of inconsistencies, and some data is just not there, so we'd still need to maintain a bunch of validations and fixes in the indexer

**Comment by Psithief** [comment]
Presumably v4 is to fix the fairly dreadful codebase. We'll see how it works out.

**Comment by taw** [comment]
Well, right now I have a script that takes some Kamigawa block data from old mtgjson (because flip cards are broken in mtgjson and have been for months now) and merges it with new mtgjson data, to get something that's usable.

By very rough estimate, there seem to be [852 "create token"](http://mtg.wtf/card?q=o%3Acreate+o%3Atoken) to [42 "put token onto the battlefield"](http://mtg.wtf/card?q=o%3Aput+o%3Atoken+o%3A%22onto+the+battlefield%22) cards, so it's like 95% done.

Not sure why there are random old texts, I assume they'll fix the rest of them eventually.

**Comment by Psithief** [comment]
It's more than 95% done now. `Alive // Well`, `Supply // Demand` need to be fixed, because gatherer changed how split cards are displayed once again.

**Comment by taw** [comment]
It really bothers me that mtgjson still didn't fix it.

**Comment by Psithief** [comment]
What got left out of https://github.com/mtgjson/mtgjson/issues/240 ?
Or did they not refresh the data since that commit?

**Comment by taw** [comment]
@Psithief It got "fixed" by reverting to old version, so cards now work but have old Oracle text.

Before the fix they were just totally broken.

**Comment by taw** [comment]
We now use all sets as they are on mtgjson except Betrayers of Kamigawa, plus some hacks to workaround known mtgjson bugs. Betrayers of Kamigawa seems to have correct wording too.

Search for [o:"put a token"](https://mtg.wtf/card?q=o%3A%22put+a+token%22) returns nothing.

As far as I can tell, all these issues are fixed now.
